[package]
name = "pic_editor_rs"
version = "0.0.1"
edition = "2021"

[dependencies]
bevy = { version = "0.15.0" }
bevy_egui = "0.31.1"
clap = { version = "4.5.23", features = ["derive"] }
image = { version = "0.25.5" }
